name: Mój workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  manual-trigger:
    runs-on: windows-latest
    steps:
      - name: Wywołaj workflow ręcznie
        run: echo "Uruchomiono workflow"

  build:
    needs: manual-trigger
    runs-on: windows-latest
    steps:
      - name: Checkout kodu
        uses: actions/checkout@v2

      - name: Ustawienia domyślnego serwera Windows
        run: |
          Start-Process wuauclt.exe /detectnow
          Start-Sleep -Seconds 10
          Start-Process wuauclt.exe /resetauthorization
          Start-Sleep -Seconds 10
          Start-Process wuauclt.exe /reportnow

      - name: Skonfiguruj i zainstaluj potrzebne komponenty np. pip i PowerShell
        run: |
          iex "& { $(irm https://aka.ms/install-powershell.ps1 -UseBasicP) }"
          iex "& { $(irm https://bootstrap.pypa.io/get-pip.py -UseBasicP) }"

      - name: Uruchom skrypt installResources.ps1
        shell: pwsh
        run: .\installResources.ps1

      - name: Budowanie pliku .exe
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python program.py

      - name: Prześlij plik .exe
        uses: actions/upload-artifact@v3
        with:
          name: Artefakcik
          path: program.exe
