name: Mój workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  manual-trigger:
    runs-on: windows-latest
    steps:
      - name: Wywołaj workflow ręcznie
        run: echo "Uruchomiono workflow"

  build:
    needs: manual-trigger
    runs-on: windows-latest
    steps:
      - name: Checkout kodu
        uses: actions/checkout@v3
        with:
          repository: Liv700/Projekt678
          ref: Task9
        
      - name: Weryfikacja sklonowanego kodu
        run: |
          git branch -a
          git ls-files
        
      - name: Pokaż bieżącą lokalizację
        run: |
          echo "Bieżąca ścieżka: $PWD"
          echo "GitHub workspace: $GITHUB_WORKSPACE"

      - name: Ustawienia domyślnego serwera Windows
        run: |
          Start-Process wuauclt.exe /detectnow
          Start-Sleep -Seconds 10
          Start-Process wuauclt.exe /resetauthorization
          Start-Sleep -Seconds 10
          Start-Process wuauclt.exe /reportnow

      - name: Skonfiguruj i zainstaluj potrzebne komponenty np. pip, powershell
        run: |
            (New-Object System.Net.WebClient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'get-pip.py')
             python get-pip.py
             iex "& { $(irm https://aka.ms/install-powershell.ps1 -UseBasicP) }"
             iex "& { $(irm https://aka.ms/install-powershell.ps1 -UseBasicP) } | Install-Module -Name PowerShellGet -Force -AllowClobber"
             

      - name: Wykonaj plik installResources.ps1
        shell: powershell
        run: |
          cd Desktop/Program
          .\installResources.ps1

# Na wypadek gdyby był problem z plikiem installResources.ps1 można osobnno poinstalować paczki:
 #     - name: Zainstaluj zależności
  #      run: |
   #       python -m pip install --upgrade pip
    #      pip install pyinstaller
     #     pip install pyyaml
      #    pip install xmldict
       #   pip install simplejson
    
      - name: Budowanie pliku .exe
        run: |
          cd Desktop/Program
          pyinstaller --onefile --noconsole --distpath . program.py

      - name: Prześlij plik .exe
        uses: actions/upload-artifact@v3
        with:
          name: Artefakcik
          path: Desktop/Program/program.exe
